### ISSUE TITLE
exec: "python": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by musicformellons** [cschaible/actix-web-security-samples#1]
When trying to run the container I get:
```
 !  ~/P/a/o/docker  sh ./up.sh                                                                                                         16.4s  Sat May  1 14:05:13 2021
Docker Compose is now in the Docker CLI, try `docker compose up`

postgres is up-to-date
pgadmin is up-to-date
docker_keycloak_1 is up-to-date
Connection to 127.0.0.1 port 5433 [tcp/pyrrho] succeeded!
OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "python": executable file not found in $PATH: unknown
```

**Comment by musicformellons** [comment]
After altering ```python``` into ```python3``` in ``` create-pgadmin-connection.sh```:
```
#!/bin/bash

docker cp ./servers.json pgadmin:/tmp/servers.json
docker exec pgadmin python /pgadmin4/setup.py --load-servers /tmp/servers.json --user "administr@t.r"
```

I get:
```
 ~/P/a/o/docker  sh ./up.sh                                                                                                            3692ms  Sat May  1 14:53:59 2021
Docker Compose is now in the Docker CLI, try `docker compose up`

postgres is up-to-date
docker_keycloak_1 is up-to-date
pgadmin is up-to-date
Connection to 127.0.0.1 port 5433 [tcp/pyrrho] succeeded!
Traceback (most recent call last):
  File "/pgadmin4/setup.py", line 31, in <module>
    from pgadmin import create_app
  File "/pgadmin4/pgadmin/__init__.py", line 21, in <module>
    from flask import Flask, abort, request, current_app, session, url_for
ModuleNotFoundError: No module named 'flask'
```

**Comment by musicformellons** [comment]
It works using older images:
```
version: "3"
services:
  pgadmin:
    image: dpage/pgadmin4:4.30
    hostname: pgadmin
    container_name: pgadmin
    ports:
      - "5433:5433"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 5433
    depends_on:
      - postgresql
  
  postgresql:
    image: postgres:9.6.20
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGPASSWORD: secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh:ro

  keycloak:
    image: quay.io/keycloak/keycloak:12.0.3
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgresql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: secret
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret
      KEYCLOAK_IMPORT: /tmp/app-realm.json
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8080:8080
    volumes:
      - ./app-realm.json:/tmp/app-realm.json:ro
    depends_on:
      - postgresql
    
```
